name: openflutterecommerce
description: A Flutter E-commerce App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.2+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^0.22.0
  flutter_translate: ^3.0.1
  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  http: ^0.13.3
  intl: ^0.17.0
  path: ^1.8.0
  rxdart: ^0.27.2
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0
  bubble_tab_indicator: ^0.1.6
  cupertino_icons: ^1.0.3
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/bottom_menu/
    - assets/icons/products/
    - assets/icons/signin/
    - assets/icons/favourites/
    - assets/images/products/
    - assets/images/checkout/
    - assets/images/checkout/cart/
    - assets/splash/
    - assets/thumbs/
    - assets/thumbs/dress/
    - assets/thumbs/products/
    - assets/thumbs/shirt/
    - assets/thumbs/category/
    - assets/i18n/
    - assets/profile/
    - assets/placeholder.png

  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Thin.otf
          weight: 100
          style: normal
        - asset: fonts/Metropolis-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/Metropolis-ExtraLight.otf
          weight: 200
          style: normal
        - asset: fonts/Metropolis-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/Metropolis-Light.otf
          weight: 300
          style: normal
        - asset: fonts/Metropolis-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/Metropolis-Regular.otf
          weight: 400
          style: normal
        - asset: fonts/Metropolis-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/Metropolis-Medium.otf
          weight: 500
          style: normal
        - asset: fonts/Metropolis-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Metropolis-SemiBold.otf
          weight: 600
          style: normal
        - asset: fonts/Metropolis-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/Metropolis-Bold.otf
          weight: 700
          style: normal
        - asset: fonts/Metropolis-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/Metropolis-ExtraBold.otf
          weight: 800
          style: normal
        - asset: fonts/Metropolis-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/Metropolis-Black.otf
          weight: 900
          style: normal
        - asset: fonts/Metropolis-BlackItalic.otf
          weight: 900
          style: italic
